import { StyleSheet } from "@react-pdf/renderer";

import { COLORS, SANS, SERIF } from "./brief-assets";

/**
 * StyleSheet del PDF del brief. ~480 LOC distribuidas en 7 secciones
 * delimitadas por comentarios. La estructura sigue el flujo del
 * documento: chrome de páginas interiores → tipografía → spacing →
 * bullets → tabla de 9 dimensiones → callouts → firma → footer →
 * cover page (página 1).
 */
export const styles = StyleSheet.create({
  // ---------- Interior page chrome ----------
  page: {
    padding: 0,
    fontFamily: SERIF,
    backgroundColor: "#FFFFFF",
    color: COLORS.ink,
    fontSize: 11,
    lineHeight: 1.6,
  },
  bandTop: { height: 7, backgroundColor: COLORS.violet },
  bandTopAccent: { height: 3, backgroundColor: COLORS.coral },
  inner: {
    paddingHorizontal: 64,
    paddingTop: 46,
    paddingBottom: 78,
    flexGrow: 1,
  },

  // ---------- Interior page header ----------
  pageHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 34,
  },
  pageHeaderEyebrow: {
    fontFamily: SANS,
    fontSize: 7.5,
    fontWeight: 600,
    letterSpacing: 3,
    color: COLORS.coral,
    textTransform: "uppercase",
  },
  pageHeaderPage: {
    fontFamily: SANS,
    fontSize: 8,
    fontWeight: 600,
    letterSpacing: 1.5,
    color: COLORS.inkMuted,
    textTransform: "uppercase",
  },

  // ---------- Typography hierarchy ----------
  sectionEyebrow: {
    fontFamily: SANS,
    fontSize: 7.5,
    fontWeight: 600,
    letterSpacing: 3,
    color: COLORS.violet,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  h1: {
    fontFamily: SERIF,
    fontWeight: 600,
    fontSize: 26,
    color: COLORS.ink,
    letterSpacing: 0,
    marginBottom: 18,
    lineHeight: 1.18,
  },
  h2: {
    fontFamily: SERIF,
    fontWeight: 600,
    fontSize: 15,
    color: COLORS.ink,
    marginBottom: 12,
    lineHeight: 1.3,
  },
  para: {
    fontFamily: SERIF,
    fontSize: 11,
    color: COLORS.ink,
    marginBottom: 13,
    textAlign: "justify",
    lineHeight: 1.65,
  },
  paraIntro: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 12,
    color: COLORS.inkSoft,
    marginBottom: 18,
    lineHeight: 1.55,
  },
  paraSmall: {
    fontFamily: SERIF,
    fontSize: 9.5,
    color: COLORS.inkSoft,
    marginBottom: 8,
    lineHeight: 1.6,
  },
  bold: {
    fontFamily: SERIF,
    fontWeight: 600,
    color: COLORS.ink,
  },
  highlight: {
    fontFamily: SERIF,
    fontWeight: 600,
    color: COLORS.violet,
  },

  // ---------- Section spacing ----------
  sectionBlock: { marginBottom: 30 },
  sectionBlockTight: { marginBottom: 22 },
  dividerThin: {
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.divider,
    marginTop: 6,
    marginBottom: 26,
  },
  rule: {
    width: 40,
    height: 2,
    backgroundColor: COLORS.coral,
    marginBottom: 14,
  },

  // ---------- Bullets ----------
  bulletList: { marginTop: 4 },
  bulletRow: {
    flexDirection: "row",
    marginBottom: 11,
    paddingLeft: 2,
  },
  bulletDot: {
    width: 14,
    fontFamily: SANS,
    fontSize: 11,
    fontWeight: 700,
    color: COLORS.coral,
    lineHeight: 1.65,
  },
  bulletNum: {
    width: 22,
    fontFamily: SANS,
    fontSize: 11,
    fontWeight: 600,
    color: COLORS.violet,
    lineHeight: 1.65,
  },
  bulletText: {
    flex: 1,
    fontFamily: SERIF,
    fontSize: 11,
    color: COLORS.ink,
    lineHeight: 1.65,
  },

  // ---------- 9 Dimensiones table ----------
  dimRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 9,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.divider,
  },
  dimRowLast: { borderBottomWidth: 0 },
  dimNum: {
    width: 34,
    fontFamily: SANS,
    fontWeight: 700,
    fontSize: 13,
    color: COLORS.violet,
  },
  dimName: {
    width: 115,
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: 11,
    color: COLORS.ink,
    letterSpacing: 0.1,
  },
  dimBloque: {
    flex: 1,
    fontFamily: SERIF,
    fontSize: 10.5,
    color: COLORS.inkSoft,
  },

  // ---------- Callouts ----------
  callout: {
    marginTop: 6,
    marginBottom: 18,
    padding: 20,
    backgroundColor: COLORS.cardTint,
    borderLeft: `3 solid ${COLORS.coral}`,
    borderRadius: 4,
  },
  calloutTitle: {
    fontFamily: SANS,
    fontSize: 7.5,
    fontWeight: 600,
    letterSpacing: 2.5,
    color: COLORS.coral,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  calloutRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  calloutLabel: {
    width: 155,
    fontFamily: SANS,
    fontSize: 9.5,
    color: COLORS.inkSoft,
    lineHeight: 1.5,
  },
  calloutValue: {
    flex: 1,
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: 10.5,
    color: COLORS.ink,
    lineHeight: 1.5,
  },
  priceBig: {
    fontFamily: SANS,
    fontWeight: 700,
    fontSize: 34,
    color: COLORS.violet,
    letterSpacing: -0.5,
  },
  priceSmall: {
    fontFamily: SERIF,
    fontSize: 9.5,
    color: COLORS.inkSoft,
    marginTop: 6,
    marginBottom: 10,
    lineHeight: 1.6,
  },

  // ---------- Signature ----------
  signatureBlock: {
    marginTop: 26,
    alignItems: "flex-start",
  },
  signatureImage: {
    width: 156,
    height: 58,
    objectFit: "contain",
  },
  signatureLine: {
    width: 230,
    borderBottomWidth: 0.8,
    borderBottomColor: COLORS.ink,
    marginTop: 2,
    marginBottom: 7,
  },
  signatureName: {
    fontFamily: SANS,
    fontWeight: 700,
    fontSize: 11.5,
    color: COLORS.ink,
  },
  signatureTitle: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 9,
    color: COLORS.inkSoft,
    marginTop: 4,
    lineHeight: 1.5,
  },

  // ---------- Interior page footer ----------
  footer: {
    position: "absolute",
    bottom: 26,
    left: 64,
    right: 64,
    flexDirection: "row",
    justifyContent: "space-between",
    fontFamily: SANS,
    fontSize: 7.5,
    fontWeight: 500,
    color: COLORS.inkMuted,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  bandBottom: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    backgroundColor: COLORS.coral,
  },
  bandBottomAccent: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 3,
    height: 7,
    backgroundColor: COLORS.violet,
  },

  // ============================================================
  // COVER PAGE
  // ============================================================
  coverPage: {
    padding: 0,
    fontFamily: SANS,
    backgroundColor: COLORS.cosmic,
    color: "#FFFFFF",
    flexDirection: "column",
  },
  coverGlowTop: {
    position: "absolute",
    top: -40,
    left: -40,
    width: 360,
    height: 360,
    backgroundColor: COLORS.violetDark,
    opacity: 0.35,
    borderRadius: 180,
  },
  coverGlowBottom: {
    position: "absolute",
    bottom: -60,
    right: -80,
    width: 380,
    height: 380,
    backgroundColor: COLORS.coral,
    opacity: 0.18,
    borderRadius: 190,
  },
  coverSpine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: 14,
    backgroundColor: COLORS.coral,
  },
  coverSpineAccent: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 14,
    width: 4,
    backgroundColor: COLORS.violet,
  },
  coverBottomBand: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 18,
    backgroundColor: COLORS.coral,
  },
  coverBottomBandAccent: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 18,
    height: 6,
    backgroundColor: COLORS.violet,
  },
  coverInner: {
    flex: 1,
    paddingTop: 64,
    paddingBottom: 96,
    paddingLeft: 70,
    paddingRight: 70,
    flexDirection: "column",
  },
  coverHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 104,
  },
  coverLogoRed: {
    width: 74,
    height: 74,
    objectFit: "contain",
  },
  coverLogoDap: {
    width: 74,
    height: 74,
    objectFit: "contain",
  },
  coverEyebrow: {
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: 9,
    letterSpacing: 4.5,
    color: COLORS.coral,
    textTransform: "uppercase",
    marginBottom: 30,
  },
  coverTitle: {
    fontFamily: SERIF,
    fontWeight: 600,
    fontSize: 50,
    color: "#FFFFFF",
    letterSpacing: -0.5,
    lineHeight: 1.05,
    marginBottom: 26,
  },
  coverTitleAccent: {
    fontFamily: SERIF,
    fontWeight: 600,
    fontStyle: "italic",
    color: COLORS.coral,
  },
  coverTagline: {
    fontFamily: SERIF,
    fontSize: 14,
    color: "rgba(255,255,255,0.82)",
    lineHeight: 1.65,
    marginBottom: 40,
    maxWidth: 420,
  },
  coverFooterRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: "auto",
  },
  coverYearBlock: { flexDirection: "column" },
  coverYearLabel: {
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: 8,
    letterSpacing: 3,
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  coverYear: {
    fontFamily: SANS,
    fontWeight: 700,
    fontSize: 56,
    color: "#FFFFFF",
    lineHeight: 1,
    letterSpacing: -1,
  },
  coverDateBlock: { alignItems: "flex-end" },
  coverDateLabel: {
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: 8,
    letterSpacing: 3,
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    marginBottom: 7,
  },
  coverDateValue: {
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: 11,
    color: "#FFFFFF",
    marginBottom: 4,
  },
  coverDateSecond: {
    fontFamily: SANS,
    fontWeight: 400,
    fontSize: 10,
    color: "rgba(255,255,255,0.72)",
  },
  coverFooterCaption: {
    fontFamily: SANS,
    fontWeight: 500,
    fontSize: 7.5,
    letterSpacing: 1.8,
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    textAlign: "center",
    position: "absolute",
    bottom: 36,
    left: 0,
    right: 0,
  },
});
